DROP TABLE IF EXISTS item;

CREATE TABLE item (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    seller TEXT NOT NULL,
    price FLOAT NOT NULL,
    description TEXT NOT NULL,
    image_path TEXT NOT NULL,
);
